export enum ErrorCode {
  INVALID_REQUEST = "INVALID_REQUEST",

  UNAUTHORIZED = "UNAUTHORIZED",

  FORBIDDEN = "FORBIDDEN",

  USER_NOT_FOUND = "USER_NOT_FOUND",

  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
